[theme]
base="light"

# [browser]
# gatherUsageStats = false

[ui]
hideSidebarNav = true  # Optionally hide the sidebar navigation.
# customMenuItems = false # Removes extra menu items.

[global]
showFooter = false

[server]
# Set the maximum idle time (in seconds) before a session expires
maxSessionIdleTimeout = 7200  # Example: 1 hour timeout

# [client]
# toolbarMode=false
# showSidebarNavigation=false

